models/ImageOption.php
<?php

namespace reseed\mediaContentManager\models;

use reseed\mediaContentManager\processors\ImageProcessor;
use yii\db\ActiveRecord;

/**
 * Class ImageOption
 *
 * @author Ivan <frostealth@frostealth.ru>
 * @since 1.0
 *
 * @property string $type
 * @property int $width
 * @property int $height
 *
 * @package reseed\mediaContentManager\models
 */
class ImageOption extends ActiveRecord
{
    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @since Ver 1.0 added on 2015.05.14
     * @access public
     *
     * @return array
     */
    public static function getDefaultOptions()
    {
        return [
            ImageProcessor::SIZE_TYPE_SMALL => [
                'width' => 50,
                'height' => 50,
            ],
            ImageProcessor::SIZE_TYPE_MEDIUM => [
                'width' => 300,
                'height' => 300,
            ],
            ImageProcessor::SIZE_TYPE_LARGE => [
                'width' => 800,
                'height' => 800,
            ],
        ];
    }

    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @since Ver 1.0 added on 2015.05.14
     * @access public
     *
     * @return array
     */
    public static function getTypeLabels()
    {
        return [
            ImageProcessor::SIZE_TYPE_SMALL => \Yii::t('mediaContentModule', 'Small'),
            ImageProcessor::SIZE_TYPE_MEDIUM => \Yii::t('mediaContentModule', 'Medium'),
            ImageProcessor::SIZE_TYPE_LARGE => \Yii::t('mediaContentModule', 'Large'),
        ];
    }

    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @since Ver 1.0 added on 2015.05.14
     * @access public
     *
     * @param string $type
     *
     * @return \reseed\mediaContentManager\models\ImageOption|null
     */
    public static function getOption($type)
    {
        /** @var ImageOption $model */
        $model = static::findOne($type);
        if (empty($model) && in_array($type, ImageProcessor::getSizeTypes())) {
            $model = new self();
            $model->type = $type;
            $model->setDefaultValues();
        }

        return $model;
    }

    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @since Ver 1.0 added on 2015.05.14
     * @access public
     *
     * @return ImageOption[]
     */
    public static function getAllOptions()
    {
        $options = static::find()->indexBy('type')->all();

        foreach (ImageProcessor::getSizeTypes() as $type) {
            if (!isset($options[$type])) {
                $option = new self();
                $option->type = $type;
                $option->setDefaultValues();

                $options[$type] = $option;
            }
        }

        rsort($options);

        return $options;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'width', 'height'], 'required'],
            [['type'], 'in', 'range' => ImageProcessor::getSizeTypes()],
            [['type'], 'unique'],
            [['width', 'height'], 'integer', 'integerOnly' => true],
        ];
    }

    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @since Ver 1.0 added on 2015.05.14
     * @access public
     *
     * @return string
     */
    public function getTypeLabel()
    {
        return self::getTypeLabels()[$this->type];
    }

    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @since Ver 1.0 added on 2015.05.14
     * @access public
     */
    public function setDefaultValues()
    {
        $this->setAttributes(self::getDefaultOptions()[$this->type]);
    }
}

controllers/DefaultController.php
<?php

namespace reseed\mediaContentManager\controllers;

use yii\web\Controller;
use reseed\mediaContentManager\models\File;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;

/**
 * Class DefaultController
 *
 * @author Ivan <frostealth@frostealth.ru>
 * @since 1.0
 *
 * @package reseed\mediaContentManager\controllers
 */
class DefaultController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'accessControl' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    
    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @version Ver 1.0 added on 2015.04.05
     * @access public
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!\Yii::$app->getUser()->can('viewFiles')) {
            throw new ForbiddenHttpException();
        }

        $dataProvider = (new File)->search();

        return $this->render('index', ['dataProvider' => $dataProvider]);
    }
}

controllers/ImageOptionsController.php
<?php

namespace reseed\mediaContentManager\controllers;

use reseed\mediaContentManager\models\ImageOption;
use yii\base\Model;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Class ImageOptionsController
 *
 * @author Ivan <frostealth@frostealth.ru>
 * @since 1.0
 *
 * @package reseed\mediaContentManager\controllers
 */
class ImageOptionsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'accessControl' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['imageOptions'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @author Ivan <frostealth@frostealth.ru>
     * @version Ver 1.0 added on 2015.05.14
     * @access public
     *
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        if (\Yii::$app->request->post('reset')) {
            ImageOption::deleteAll();
            \Yii::$app->getSession()->setFlash('success', 'Success reset');

            return $this->refresh();
        }

        $models = ImageOption::getAllOptions();
        if (Model::loadMultiple($models, \Yii::$app->request->post()) && Model::validateMultiple($models)) {
            foreach ($models as $model) {
                $model->save(false);
            }

            \Yii::$app->getSession()->setFlash('success', 'Success saved');

            return $this->refresh();
        }

        return $this->render('index', ['models' => $models]);
    }
}

views/image-options/index.php
<?php
/**
 * @var \yii\web\View $this
 * @var \reseed\mediaContentManager\models\ImageOption[] $models
 * @var \yii\widgets\ActiveForm $form
 */

$this->title = Yii::t('mediaContentManager', 'Image Options');
$this->params['breadcrumbs'] = [
    ['label' => Yii::t('mediaContentManager', 'Media Content Manager'), 'url' => ['default/index']],
    $this->title,
];
?>

<h1 class="page-header margin_btm_20"><?= $this->title ?></h1>

<?php $form = \yii\widgets\ActiveForm::begin() ?>

<div class="image-options-from">
    <?php if (Yii::$app->getSession()->hasFlash('success')): ?>
        <div class="alert alert-success">
            <p><?= Yii::$app->getSession()->getFlash('success') ?></p>
        </div>
    <?php endif ?>

    <?php foreach ($models as $index => $model): ?>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <?= $model->getTypeLabel() ?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model, "[$index]width")->textInput() ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field($model, "[$index]height")->textInput() ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach ?>

    <div class="form-group">
        <?= \yii\helpers\Html::submitButton(
            Yii::t('mediaContentManager', 'Save'),
            ['class' => 'btn btn-primary']
        ) ?>
        <?= \yii\helpers\Html::submitInput(
            Yii::t('mediaContentManager', 'Reset'),
            [
                'class' => 'btn btn-danger pull-right',
                'name' => 'reset',
            ]
        ) ?>
    </div>
</div>

<?php \yii\widgets\ActiveForm::end() ?>